import { Bebas_Neue, Inter, Montserrat } from 'next/font/google'
import localFont from 'next/font/local'
// import "bootstrap/dist/css/bootstrap.min.css";
// import '../globals.css'
import NextAuthProvider from '../NextAuthProvider';

const inter = Inter({ subsets: ['latin'], variable:"--font-inter", })
const montserrat = Montserrat({ subsets: ['latin'], variable:"--font-montserrat" })
const bebas_neue = localFont({
  src:"../bebas_neue_font/BebasNeue-Regular.ttf",
  display:"swap"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ExpertDashboardLayout({ children }) {
  return (
    <NextAuthProvider>
      <section className={`${montserrat.variable} ${bebas_neue.className}`}>{children}</section>
    </NextAuthProvider>
  )
}
